# Generated by Django 5.0.1 on 2024-01-17 21:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='country name')),
                ('iso_code_2d', models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='iso code 2d')),
                ('iso_code_3d', models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='iso code 3d')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'Country',
                'indexes': [models.Index(fields=['name'], name='Country_name_8a087b_idx'), models.Index(fields=['iso_code_2d'], name='Country_iso_cod_b6d562_idx'), models.Index(fields=['iso_code_3d'], name='Country_iso_cod_7b5b69_idx')],
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=20, verbose_name='ip address')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='ip.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'IPs',
                'db_table': 'IP',
                'indexes': [models.Index(fields=['address'], name='IP_address_e7ed83_idx'), models.Index(fields=['country'], name='IP_country_874bbd_idx')],
            },
        ),
    ]
