# Generated by Django 5.0.1 on 2024-01-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='country',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='modified_date',
        ),
    ]
